name:                mep
version:             0.1.0.0
github:              "shamil-gadelshin/mutual-exclusion-protocol"
license:             MIT
author:              "Shamil Gadelshin"
maintainer:          ""
copyright:           "2021 Shamil Gadelshin"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Mutual exclusion protocol based on Lamport algorithm.
# category:            Distributed systems

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/shamil-gadelshin/mutual-exclusion-protocol#readme>

dependencies:
- base >= 4.7 && < 5
- hedis
- mtl
- bytestring
- bytestring-conversion
- cmdargs
- text
- aeson
- aeson-pretty
- either
- time
- network
- pqueue
- uuid
- random
- lens
- unordered-containers

library:
  source-dirs: src

executables:
  mep:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mep

tests:
  mep-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mep
